"""added default user

Revision ID: 405e4ca5fbfe
Revises: 2f54a6a68580
Create Date: 2024-06-09 13:33:03.612137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "405e4ca5fbfe"
down_revision: Union[str, None] = "2f54a6a68580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """insert into users (first_name, last_name, address, phone, password,email, is_active_user) 
        values ('vishw', 'kadu', 'Ahmedabad', '8128347277', 'Test@1234','vishw@test.com', true)"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
