"""add default company data

Revision ID: c19d3bf4d552
Revises: 540f66b43b2e
Create Date: 2024-06-09 19:09:51.593678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19d3bf4d552'
down_revision: Union[str, None] = '540f66b43b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""insert into companies (company_name, address, phone) values
               ('IBM', 'Mumbai', '1234567891'),
               ('Google', 'Bagaluru', '2234567891'),
               ('ReverseBit', 'Ahmedabad', '1334567891'),
               ('FX', 'Ahmedabad', '1334567891'),
               ('TCS', 'Ahmedabad', '1534567891')
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
